// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerCurrency } from "./LedgerCurrency";
import type { LedgerFiscalCalendar } from "./LedgerFiscalCalendar";

export type LedgerCreateCompanyParams = { name: string, baseCurrency: LedgerCurrency, fiscalCalendar: LedgerFiscalCalendar, };
