// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerAuditEvent } from "./LedgerAuditEvent";

export type LedgerListAuditTrailResponse = { events: Array<LedgerAuditEvent>, nextCursor: string | null, };
