// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerSuggestedLine } from "./LedgerSuggestedLine";

export type LedgerJournalEntrySuggestion = { lines: Array<LedgerSuggestedLine>, memo: string, confidence: number, reasoning: string, };
