// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerPeriodAction } from "./LedgerPeriodAction";
import type { LedgerPeriodRef } from "./LedgerPeriodRef";

export type LedgerLockPeriodParams = { companyId: string, journalId: string, period: LedgerPeriodRef, action: LedgerPeriodAction, approvalReference: string | null, };
