// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerCurrency } from "./LedgerCurrency";
import type { LedgerCurrencyRate } from "./LedgerCurrencyRate";
import type { LedgerPostingSide } from "./LedgerPostingSide";
import type { LedgerTaxCode } from "./LedgerTaxCode";

export type LedgerJournalLine = { id: string, accountId: string, side: LedgerPostingSide, amountMinor: bigint, currency: LedgerCurrency, functionalAmountMinor: bigint, functionalCurrency: LedgerCurrency, exchangeRate: LedgerCurrencyRate | null, taxCode: LedgerTaxCode | null, memo: string | null, };
