// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerEntryOrigin } from "./LedgerEntryOrigin";
import type { LedgerEntryStatus } from "./LedgerEntryStatus";
import type { LedgerJournalLine } from "./LedgerJournalLine";
import type { LedgerReconciliationStatus } from "./LedgerReconciliationStatus";

export type LedgerJournalEntry = { id: string, journalId: string, status: LedgerEntryStatus, reconciliationStatus: LedgerReconciliationStatus, lines: Array<LedgerJournalLine>, origin: LedgerEntryOrigin, memo: string | null, reversesEntryId: string | null, reversedByEntryId: string | null, };
