// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerAccountType } from "./LedgerAccountType";
import type { LedgerCurrencyMode } from "./LedgerCurrencyMode";
import type { LedgerTaxCode } from "./LedgerTaxCode";

export type LedgerAccount = { id: string, companyId: string, code: string, name: string, accountType: LedgerAccountType, parentAccountId: string | null, currencyMode: LedgerCurrencyMode, taxCode: LedgerTaxCode | null, isSummary: boolean, isActive: boolean, };
