// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerCurrency } from "./LedgerCurrency";
import type { LedgerPeriodRef } from "./LedgerPeriodRef";

export type LedgerRevalueCurrencyParams = { companyId: string, journalId: string, period: LedgerPeriodRef, currencies: Array<LedgerCurrency>, };
