// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerJournalType } from "./LedgerJournalType";
import type { LedgerPeriodLock } from "./LedgerPeriodLock";
import type { LedgerPeriodState } from "./LedgerPeriodState";

export type LedgerJournal = { id: string, companyId: string, ledgerType: LedgerJournalType, periodState: LedgerPeriodState, latestLock: LedgerPeriodLock | null, lockHistory?: Array<LedgerPeriodLock>, };
