// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerJournalEntry } from "./LedgerJournalEntry";

export type LedgerReverseEntryResponse = { entry: LedgerJournalEntry, };
