// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LedgerReconciliationStatus = "unreconciled" | { "pending": { session_id: string, } } | { "reconciled": { session_id: string, } } | { "writeOff": { approval_reference: string, } };
