// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerAccount } from "./LedgerAccount";
import type { LedgerJournalEntry } from "./LedgerJournalEntry";
import type { LedgerPolicyRules } from "./LedgerPolicyRules";

export type LedgerGetCompanyContextResponse = { chartOfAccounts: Array<LedgerAccount>, recentTransactions: Array<LedgerJournalEntry>, vendorMappings: { [key in string]?: string }, policyRules: LedgerPolicyRules, };
