// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAuthStatus } from "./McpAuthStatus";
import type { Tool } from "./Tool";

export type McpListToolsResponseEvent = { 
/**
 * Fully qualified tool name -> tool definition.
 */
tools: { [key in string]?: Tool }, 
/**
 * Authentication status for each configured MCP server.
 */
auth_statuses: { [key in string]?: McpAuthStatus }, };
